apiVersion: v1
kind: Pod

metadata:
  name: liveness-pod
spec:
  containers:
    - name:  liveness-container-test
      image: busybox
      args:
      - /bib/sh
      - c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600

      livenessProbe:
        exec:
          command:
          - vat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
