kind: ConfigMap
apiVersion: v1
metadata:
  name: my-cm
  namespace: default
data:
  #Connection database config
  database: mysql
  database_uri: mysql://localhost:33306

  font.title: Arial Bold
  background-color: red
  theme.1: clean
  thema.2: dark
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-cm-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - configMapRef:
        name: my-cm
